/**
 * Typed fetch wrapper — the single way the frontend talks to the API.
 *
 * Responsibilities (design-system.md "API client"):
 *  - attach the Amplify ID token as `Authorization: Bearer <token>`
 *  - serialize JSON in/out and build query strings
 *  - parse the standard error envelope and throw a typed {@link ApiError}
 *
 * Modules call these generic methods (`api.get`, `api.post`, …) with their own
 * path + response type; they never use raw `fetch`. They do NOT edit this file —
 * resource-specific calls live in each module under its own directory.
 *
 * `createApiClient` is a factory so the token provider and `fetch` can be injected
 * in tests. The default singleton `api` is wired to Amplify + `VITE_API_BASE_URL`.
 */
import { ApiError, STATUS_TO_CODE, type ApiErrorEnvelope, type Query } from "./types";

/** Returns the current ID token, or null if the user is not authenticated. */
export type TokenProvider = () => Promise<string | null>;

export interface ApiClientConfig {
  /** API base URL, no trailing slash (e.g. https://abc.execute-api.us-east-2.amazonaws.com). */
  baseUrl: string;
  /** How to obtain the bearer token for each request. */
  getToken: TokenProvider;
  /** Injectable fetch (defaults to global fetch); used by tests. */
  fetchImpl?: typeof fetch;
}

export interface RequestOptions {
  query?: Query;
  /** JSON-serializable request body. */
  body?: unknown;
  /** Extra headers (merged after the defaults; cannot drop Authorization). */
  headers?: Record<string, string>;
  signal?: AbortSignal;
}

export interface ApiClient {
  readonly baseUrl: string;
  request<T = unknown>(method: string, path: string, opts?: RequestOptions): Promise<T>;
  get<T = unknown>(path: string, opts?: Omit<RequestOptions, "body">): Promise<T>;
  post<T = unknown>(path: string, body?: unknown, opts?: Omit<RequestOptions, "body">): Promise<T>;
  put<T = unknown>(path: string, body?: unknown, opts?: Omit<RequestOptions, "body">): Promise<T>;
  patch<T = unknown>(path: string, body?: unknown, opts?: Omit<RequestOptions, "body">): Promise<T>;
  del<T = unknown>(path: string, opts?: Omit<RequestOptions, "body">): Promise<T>;
}

function buildQuery(query?: Query): string {
  if (!query) return "";
  const params = new URLSearchParams();
  for (const [key, value] of Object.entries(query)) {
    if (value === undefined || value === null) continue;
    params.append(key, String(value));
  }
  const qs = params.toString();
  return qs ? `?${qs}` : "";
}

function joinUrl(baseUrl: string, path: string): string {
  const base = baseUrl.replace(/\/+$/, "");
  const rel = path.startsWith("/") ? path : `/${path}`;
  return `${base}${rel}`;
}

/** Parse a failed response into a typed ApiError, tolerating non-JSON bodies. */
async function toApiError(res: Response): Promise<ApiError> {
  const fallbackCode = STATUS_TO_CODE[res.status] ?? "internal";
  let code: string = fallbackCode;
  let message = res.statusText || "Request failed";
  try {
    const data = (await res.json()) as Partial<ApiErrorEnvelope>;
    if (data && typeof data === "object" && data.error) {
      code = data.error.code || fallbackCode;
      message = data.error.message || message;
    }
  } catch {
    // Non-JSON / empty body — keep the status-derived defaults.
  }
  return new ApiError(res.status, code, message);
}

export function createApiClient(config: ApiClientConfig): ApiClient {
  const doFetch = config.fetchImpl ?? globalThis.fetch.bind(globalThis);

  async function request<T = unknown>(
    method: string,
    path: string,
    opts: RequestOptions = {},
  ): Promise<T> {
    const url = joinUrl(config.baseUrl, path) + buildQuery(opts.query);

    const headers: Record<string, string> = { Accept: "application/json", ...opts.headers };
    const token = await config.getToken();
    if (token) headers["Authorization"] = `Bearer ${token}`;

    const hasBody = opts.body !== undefined;
    if (hasBody) headers["Content-Type"] = "application/json";

    const res = await doFetch(url, {
      method,
      headers,
      body: hasBody ? JSON.stringify(opts.body) : undefined,
      signal: opts.signal,
    });

    if (!res.ok) throw await toApiError(res);

    // 204 No Content (or empty body) — nothing to parse.
    if (res.status === 204) return undefined as T;
    const text = await res.text();
    if (!text) return undefined as T;
    return JSON.parse(text) as T;
  }

  return {
    baseUrl: config.baseUrl,
    request,
    get: (path, opts) => request("GET", path, opts),
    post: (path, body, opts) => request("POST", path, { ...opts, body }),
    put: (path, body, opts) => request("PUT", path, { ...opts, body }),
    patch: (path, body, opts) => request("PATCH", path, { ...opts, body }),
    del: (path, opts) => request("DELETE", path, opts),
  };
}
