#!/usr/bin/env node
// build:lambda — turn backend/ into deployable Lambda assets.
//
// Two steps, deterministic and offline:
//   1. Codegen backend/lambda/generated/manifests.ts — a barrel that STATICALLY imports every
//      module's routes.manifest so esbuild can tree-bundle the router. (The shared loadManifests
//      does a runtime fs-scan + dynamic import, which a single-file bundle breaks.)
//   2. esbuild-bundle the two Lambda entries into single CJS files:
//        backend/lambda/api.ts       -> backend/dist/api/index.js        (handler: index.handler)
//        backend/lambda/hydration.ts -> backend/dist/hydration/index.js  (handler: index.handler)
//
// CDK points Code.fromAsset at backend/dist/api and backend/dist/hydration. No node_modules ship.

import { build } from 'esbuild';
import { existsSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const backendDir = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const modulesDir = join(backendDir, 'modules');
const generatedFile = join(backendDir, 'lambda', 'generated', 'manifests.ts');

/** kebab/snake module dir name -> camelCase identifier (activity-journal -> activityJournal). */
function toIdentifier(name) {
  return name.replace(/[-_]+([a-z0-9])/g, (_, c) => c.toUpperCase());
}

/** Discover module dirs that ship a route manifest, sorted for deterministic output. */
function findModules() {
  if (!existsSync(modulesDir)) return [];
  return readdirSync(modulesDir, { withFileTypes: true })
    .filter((d) => d.isDirectory() && existsSync(join(modulesDir, d.name, 'routes.manifest.ts')))
    .map((d) => d.name)
    .sort();
}

function generateManifestBarrel(modules) {
  const imports = modules
    .map(
      (m) =>
        `import { routes as ${toIdentifier(m)}Routes } from '../../modules/${m}/routes.manifest.js';`,
    )
    .join('\n');
  const entries = modules.map((m) => `  { routes: ${toIdentifier(m)}Routes },`).join('\n');

  const contents = `// AUTO-GENERATED by backend/scripts/build-lambda.mjs — do not edit by hand.
// Static imports of every module route manifest so esbuild can bundle the Lambda into a single
// file without a runtime filesystem scan (loadManifests' dynamic import does not survive bundling).
// Regenerated on every \`npm run -w backend build:lambda\`; committed so \`tsc --noEmit\` typechecks
// the entry. If you add a module, run the build (or \`gen:manifests\`) to refresh this list.
import type { RouteManifest } from '../../shared/api/index.js';
${imports}

export const manifests: RouteManifest[] = [
${entries}
];
`;

  mkdirSync(dirname(generatedFile), { recursive: true });
  writeFileSync(generatedFile, contents);
}

async function bundle(entryRelPath, outSubdir) {
  const outDir = join(backendDir, 'dist', outSubdir);
  await build({
    entryPoints: [join(backendDir, entryRelPath)],
    outfile: join(outDir, 'index.js'),
    bundle: true,
    platform: 'node',
    target: 'node20',
    format: 'cjs',
    sourcemap: false,
    minify: false,
    logLevel: 'warning',
  });
  // backend/package.json is `type: module`, which would make Node parse the CJS bundle's
  // index.js as ESM (and `exports`/`require` would break). A sidecar package.json pins the
  // asset dir to CommonJS so the Lambda runtime loads `index.handler` correctly.
  writeFileSync(join(outDir, 'package.json'), `${JSON.stringify({ type: 'commonjs' }, null, 2)}\n`);
}

const modules = findModules();
generateManifestBarrel(modules);
console.log(
  `gen:manifests — ${modules.length} module manifest(s): ${modules.join(', ') || '(none)'}`,
);

await bundle('lambda/api.ts', 'api');
await bundle('lambda/hydration.ts', 'hydration');

console.log('build:lambda — wrote backend/dist/api/index.js and backend/dist/hydration/index.js');
