#!/usr/bin/env node
// build:lambda — turn backend/ into deployable Lambda assets.
//
// Three steps, deterministic and offline:
//   1. Codegen backend/lambda/generated/manifests.ts — a barrel that STATICALLY imports every
//      module's routes.manifest so esbuild can tree-bundle the router. (The shared loadManifests
//      does a runtime fs-scan + dynamic import, which a single-file bundle breaks.)
//   2. Codegen backend/lambda/generated/hydration-manifests.ts — the same trick for the SQS worker:
//      statically import each module's hydration.manifest so its handler is bundled into the worker
//      and registered by message `type` (an fs-scan/dynamic-import would not survive bundling).
//   3. esbuild-bundle the two Lambda entries into single CJS files:
//        backend/lambda/api.ts       -> backend/dist/api/index.js        (handler: index.handler)
//        backend/lambda/hydration.ts -> backend/dist/hydration/index.js  (handler: index.handler)
//
// CDK points Code.fromAsset at backend/dist/api and backend/dist/hydration. No node_modules ship.

import { build } from 'esbuild';
import { existsSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const backendDir = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const modulesDir = join(backendDir, 'modules');
const routesBarrel = join(backendDir, 'lambda', 'generated', 'manifests.ts');
const hydrationBarrel = join(backendDir, 'lambda', 'generated', 'hydration-manifests.ts');

/** kebab/snake module dir name -> camelCase identifier (activity-journal -> activityJournal). */
function toIdentifier(name) {
  return name.replace(/[-_]+([a-z0-9])/g, (_, c) => c.toUpperCase());
}

/** Discover module dirs that ship `manifestBasename`, sorted for deterministic output. */
function findModules(manifestBasename) {
  if (!existsSync(modulesDir)) return [];
  return readdirSync(modulesDir, { withFileTypes: true })
    .filter((d) => d.isDirectory() && existsSync(join(modulesDir, d.name, manifestBasename)))
    .map((d) => d.name)
    .sort();
}

function writeBarrel(file, contents) {
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, contents);
}

function generateRoutesBarrel(modules) {
  const imports = modules
    .map(
      (m) =>
        `import { routes as ${toIdentifier(m)}Routes } from '../../modules/${m}/routes.manifest.js';`,
    )
    .join('\n');
  const entries = modules.map((m) => `  { routes: ${toIdentifier(m)}Routes },`).join('\n');

  writeBarrel(
    routesBarrel,
    `// AUTO-GENERATED by backend/scripts/build-lambda.mjs — do not edit by hand.
// Static imports of every module route manifest so esbuild can bundle the Lambda into a single
// file without a runtime filesystem scan (loadManifests' dynamic import does not survive bundling).
// Regenerated on every \`npm run -w backend build:lambda\`; committed so \`tsc --noEmit\` typechecks
// the entry. If you add a module, run the build (or \`gen:manifests\`) to refresh this list.
import type { RouteManifest } from '../../shared/api/index.js';
${imports}

export const manifests: RouteManifest[] = [
${entries}
];
`,
  );
}

/**
 * Mirror the routes barrel for the SQS worker. Each hydrating module ships
 * `hydration.manifest.ts` exporting `export const hydration = { type, handler }`; this barrel
 * statically imports each so the worker bundle (backend/lambda/hydration.ts) can register them by
 * `type`. Empty list when no module hydrates yet — still valid TS so `tsc --noEmit` passes.
 */
function generateHydrationBarrel(modules) {
  const imports = modules
    .map(
      (m) =>
        `import { hydration as ${toIdentifier(m)}Hydration } from '../../modules/${m}/hydration.manifest.js';`,
    )
    .join('\n');
  const importBlock = imports ? `${imports}\n` : '';
  const entries = modules.map((m) => `  ${toIdentifier(m)}Hydration,`).join('\n');

  writeBarrel(
    hydrationBarrel,
    `// AUTO-GENERATED by backend/scripts/build-lambda.mjs — do not edit by hand.
// Static imports of every module hydration manifest so esbuild bundles each SQS handler into the
// worker (backend/lambda/hydration.ts builds its registry from these). Regenerated on every
// \`npm run -w backend build:lambda\`; committed so \`tsc --noEmit\` typechecks the worker entry.
import type { HydrationRegistration } from '../hydration.js';
${importBlock}
export const hydrationRegistrations: HydrationRegistration[] = [
${entries}
];
`,
  );
}

async function bundle(entryRelPath, outSubdir) {
  const outDir = join(backendDir, 'dist', outSubdir);
  await build({
    entryPoints: [join(backendDir, entryRelPath)],
    outfile: join(outDir, 'index.js'),
    bundle: true,
    platform: 'node',
    target: 'node20',
    format: 'cjs',
    sourcemap: false,
    minify: false,
    logLevel: 'warning',
  });
  // backend/package.json is `type: module`, which would make Node parse the CJS bundle's
  // index.js as ESM (and `exports`/`require` would break). A sidecar package.json pins the
  // asset dir to CommonJS so the Lambda runtime loads `index.handler` correctly.
  writeFileSync(join(outDir, 'package.json'), `${JSON.stringify({ type: 'commonjs' }, null, 2)}\n`);
}

const routeModules = findModules('routes.manifest.ts');
generateRoutesBarrel(routeModules);
console.log(
  `gen:manifests (routes) — ${routeModules.length}: ${routeModules.join(', ') || '(none)'}`,
);

const hydrationModules = findModules('hydration.manifest.ts');
generateHydrationBarrel(hydrationModules);
console.log(
  `gen:manifests (hydration) — ${hydrationModules.length}: ${hydrationModules.join(', ') || '(none)'}`,
);

await bundle('lambda/api.ts', 'api');
await bundle('lambda/hydration.ts', 'hydration');
await bundle('lambda/digest.ts', 'digest');

console.log(
  'build:lambda — wrote backend/dist/{api,hydration,digest}/index.js',
);
