import { useCallback, useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";
import { Badge, Button, Card, EmptyState, Icon, Spinner } from "../../shared/ui";
import { useActiveStudent } from "../../shared/shell";
import { getFocus, refreshOverview } from "./api";
import type { FocusResponse, PackSummary } from "./types";
import { Markdown } from "./Markdown";

/** A heading row for a pack content section. */
function SectionTitle({ children }: { children: React.ReactNode }) {
  return <h2 className="mb-2 text-sm font-semibold text-ink-800">{children}</h2>;
}

/** The curated, instant pack content (exam, certs, questions) — what's tailored, with deep links. */
function PackDetails({ pack }: { pack: PackSummary }) {
  return (
    <div className="space-y-4">
      {pack.entranceExam ? (
        <Card>
          <SectionTitle>Entrance exam</SectionTitle>
          <Link to="/exams" className="group flex items-center justify-between gap-2">
            <div>
              <p className="font-semibold text-ink-900">{pack.entranceExam.examName}</p>
              {pack.entranceExam.competitiveScore != null ? (
                <p className="text-xs text-ink-500">Competitive score ≈ {pack.entranceExam.competitiveScore}</p>
              ) : null}
              {pack.entranceExam.note ? <p className="mt-0.5 text-xs text-ink-500">{pack.entranceExam.note}</p> : null}
            </div>
            <Badge tone="primary">Test Prep <Icon name="chevron-right" size={13} /></Badge>
          </Link>
        </Card>
      ) : null}

      {pack.certifications.length > 0 ? (
        <Card>
          <SectionTitle>Recommended certifications</SectionTitle>
          <ul className="divide-y divide-surface-border">
            {pack.certifications.map((c) => (
              <li key={c.name} className="py-2">
                <p className="text-sm font-medium text-ink-900">
                  {c.name}
                  {c.issuingOrganization ? <span className="font-normal text-ink-400"> · {c.issuingOrganization}</span> : null}
                </p>
                <p className="text-xs text-ink-500">{c.why}</p>
              </li>
            ))}
          </ul>
          <Link to="/certifications" className="mt-2 inline-flex items-center gap-1 text-xs font-medium text-primary-600 hover:text-primary-700">
            Track certifications <Icon name="chevron-right" size={13} />
          </Link>
        </Card>
      ) : null}

      {pack.interviewQuestions.length > 0 ? (
        <Card>
          <SectionTitle>Interview questions to prepare</SectionTitle>
          <ul className="list-disc space-y-1 pl-5 text-sm text-ink-700">
            {pack.interviewQuestions.map((q) => <li key={q}>{q}</li>)}
          </ul>
          <Link to="/interviews" className="mt-2 inline-flex items-center gap-1 text-xs font-medium text-primary-600 hover:text-primary-700">
            Practice interviews <Icon name="chevron-right" size={13} />
          </Link>
        </Card>
      ) : null}

      {pack.visitQuestions.length > 0 ? (
        <Card>
          <SectionTitle>Ask on campus visits</SectionTitle>
          <ul className="list-disc space-y-1 pl-5 text-sm text-ink-700">
            {pack.visitQuestions.map((q) => <li key={q}>{q}</li>)}
          </ul>
          <Link to="/visits" className="mt-2 inline-flex items-center gap-1 text-xs font-medium text-primary-600 hover:text-primary-700">
            Plan a visit <Icon name="chevron-right" size={13} />
          </Link>
        </Card>
      ) : null}
    </div>
  );
}

export default function FocusPage() {
  const { activeStudentId } = useActiveStudent();
  const [data, setData] = useState<FocusResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);
  const pollRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const load = useCallback(async () => {
    try {
      setData(await getFocus());
      setError(null);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Could not load your focus.");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    setLoading(true);
    void load();
  }, [load, activeStudentId]);

  // Poll while the overview is being generated by the worker.
  useEffect(() => {
    if (data?.overview?.status === "pending") {
      pollRef.current = setTimeout(() => void load(), 4000);
      return () => {
        if (pollRef.current) clearTimeout(pollRef.current);
      };
    }
  }, [data?.overview?.status, data?.overview?.updatedAt, load]);

  async function generate() {
    setGenerating(true);
    try {
      await refreshOverview();
      await load();
    } catch (e) {
      setError(e instanceof Error ? e.message : "Could not start the overview.");
    } finally {
      setGenerating(false);
    }
  }

  if (loading) return <div className="flex justify-center py-24"><Spinner size={28} /></div>;

  if (error && !data) {
    return (
      <div className="mx-auto max-w-2xl p-6">
        <Card className="border border-error-200 bg-error-50 text-error-700">
          <p className="text-sm">{error}</p>
          <Button className="mt-2" size="sm" variant="outline" onClick={() => { setLoading(true); void load(); }}>Retry</Button>
        </Card>
      </div>
    );
  }

  // No major set yet → point to the Family page where it's chosen.
  if (!data || data.packs.length === 0) {
    return (
      <div className="mx-auto max-w-3xl p-4 sm:p-6">
        <EmptyState
          icon="star"
          title="Pick an academic focus"
          description="Set an intended major on the Family page and this becomes your major hub — a tailored overview, the entrance exam, recommended certifications, and the questions to ask, all in one place."
        />
        <div className="mt-4 flex justify-center">
          <Link to="/family"><Button>Set intended major</Button></Link>
        </div>
      </div>
    );
  }

  const ov = data.overview;

  return (
    <div className="mx-auto max-w-3xl space-y-5 p-4 sm:p-6">
      <header className="flex flex-wrap items-center gap-2">
        <h1 className="text-2xl font-bold text-ink-900">Your focus</h1>
        {data.packs.map((p) => <Badge key={p.key} tone="primary">{p.label}</Badge>)}
      </header>
      <p className="-mt-2 text-sm text-ink-500">
        {data.careerGoal ? `Toward your goal: ${data.careerGoal}. ` : ""}
        Everything below is tailored to this focus, and the AI across the app uses it too.
      </p>

      {/* AI web-grounded overview */}
      <Card>
        <div className="mb-2 flex items-center justify-between gap-2">
          <SectionTitle>Overview</SectionTitle>
          {ov?.status === "complete" && !data.stale ? (
            <Button size="sm" variant="outline" onClick={generate} disabled={generating}>Refresh</Button>
          ) : null}
        </div>

        {ov?.status === "pending" || generating ? (
          <div className="flex items-center gap-3 py-6 text-sm text-ink-500">
            <Spinner size={20} /> Researching {data.packs[0]?.label} on the web… this takes up to a minute.
          </div>
        ) : ov?.status === "complete" ? (
          <>
            {data.stale ? (
              <div className="mb-3 rounded-lg border border-warn-200 bg-warn-50 px-3 py-2 text-xs text-warn-800">
                Your major changed since this was written. <button onClick={generate} className="font-semibold underline">Refresh it</button>.
              </div>
            ) : null}
            {ov.overview ? <Markdown text={ov.overview} /> : null}
            {ov.sources && ov.sources.length > 0 ? (
              <div className="mt-4 border-t border-surface-border pt-3">
                <p className="mb-1 text-xs font-medium uppercase tracking-wide text-ink-400">Sources</p>
                <ul className="space-y-1">
                  {ov.sources.map((s, i) => (
                    <li key={i} className="truncate text-xs">
                      <a href={s.url} target="_blank" rel="noreferrer" className="text-primary-600 hover:text-primary-700">{s.title}</a>
                    </li>
                  ))}
                </ul>
              </div>
            ) : null}
          </>
        ) : ov?.status === "failed" ? (
          <div className="py-2">
            <p className="text-sm text-error-600">The overview couldn't be generated{ov.error ? `: ${ov.error}` : "."}</p>
            <Button className="mt-2" size="sm" onClick={generate} disabled={generating}>Try again</Button>
          </div>
        ) : (
          <div className="py-2">
            <p className="text-sm text-ink-500">Get an AI overview of pursuing {data.packs.map((p) => p.label).join(" + ")} — what it involves, how to prepare, and the career outlook, grounded in current web sources.</p>
            <Button className="mt-3" onClick={generate} disabled={generating}>Generate overview</Button>
          </div>
        )}
      </Card>

      {data.packs.map((p) => <PackDetails key={p.key} pack={p} />)}
    </div>
  );
}
